---
title: "statk"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(knitr)
library(ggplot2)
library(Kmedians)
library(NbClust)
library(haven)
library(factoextra)
library(cluster)
library(corrplot)
library(emmeans)
library(rstatix)
library(klustR)
library(plotly)
```


```{r}
batter <- read_csv("mlbBatter22-23.csv", show_col_types = FALSE)
pitcher <- read_csv("mlbPitcher22-23.csv", show_col_types = FALSE)
allplayers <- read_csv("allplayers.csv", show_col_types = FALSE)

batterClust <- batter  %>% select(- `last_name, first_name`, -player_id, -year) 
colnames(batterClust) <- c("","","","","","","","","","")
batterClust

batterClust1 <- batter  %>% select(- `last_name, first_name`,-salary, -player_id, -year) 
colnames(batterClust) <- c("","","","","","","","","","")



pitcherClust <- pitcher  %>% select(- `last_name, first_name`, -player_id, -year) 
colnames(pitcherClust) <- c("","","","","","","","","","")
pitcherClust



pitcherClust1 <- pitcher  %>% select(- `last_name, first_name`, -salary,  -player_id, -year) 
colnames(pitcherClust) <- c("","","","","","","","","","")



allclust <- allplayers  %>% select(- `last_name, first_name`, -player_id, -year) 
colnames(allclust) <- c("","","","","","","","","","")
allclust



allclust1 <- allplayers  %>% select(- `last_name, first_name`, -salary,  -player_id, -year) 
colnames(allclust1) <- c("","","","","","","","","","")
allclust1


pcabatter <- batter %>% select(-`last_name, first_name`,- player_id, -year, -salary)
pcapitcher <- pitcher %>% select(-`last_name, first_name`,- player_id, -year, -salary)
pcaall <- allplayers %>% select(-`last_name, first_name`,- player_id, -year, -salary)


```

```{r}
scale_pitcher <- scale(pitcherClust1)
scale_batter <- scale(batterClust1)
scale_all <- scale(allclust1)
```




```{r}
nb <- as.matrix(batterClust) %>% NbClust(diss=NULL, distance = "euclidean", min.nc = 2, max.nc=15, method = "centroid", index = "silhouette", alphaBeale = 0.1)




nb1 <- as.matrix(pitcherClust) %>% NbClust(diss=NULL, distance = "euclidean", min.nc = 2, max.nc=15, method = "centroid", index = "silhouette", alphaBeale = 0.1)

fviz_nbclust(scale_batter, FUNcluster = cluster::pam ,  method = "silhouette", diss = NULL, k.max=15) + ggtitle("Optimal Number of Clusters for Batters Using PAM")


fviz_nbclust(scale_pitcher, FUNcluster = cluster::pam ,  method = "silhouette", diss = NULL, k.max=15) + ggtitle("Optimal Number of Clusters for Pitchers Using PAM")

 

fviz_nbclust(scale_all, FUNcluster = cluster::pam ,  method = "silhouette", diss = NULL, k.max=15)
```
```{r}
pcabatter_norm <- scale(pcabatter)
pcapitcher_norm <- scale(pcapitcher)
pcaall_norm <- scale(pcaall)

pcabatter_corr <- cor(pcabatter_norm)
pcabatterpca <- princomp(pcabatter_corr)

pcapitcher_corr <- cor(pcapitcher_norm)
pcapitcherpca <- princomp(pcapitcher_corr)

pcaall_corr <- cor(pcaall_norm)
pcaallpca <- princomp(pcaall_corr)


fviz_pca_var(pcabatterpca, col.var = "cos2",  gradient.cols = c("black", "red", "blue"), repel = TRUE)
fviz_cos2(pcabatterpca, choice = "var", axes = 1:2) + scale_x_discrete(label = c("Single", "Batting Avg","XLSO", "XBA", "XSLG",  "Home Run", "Hit", "On Base + SLG", "OBP", "SLG%", "Exit Velocity Avg", "XOBP", "Strikeout", "Launch Angle Avg", "Walk","Double", "AB", "Triple", "Player Age")) + ggtitle("Cos2 Of Variables Assigned to Dimension 1 and 2 (Batters)")

fviz_pca_var(pcapitcherpca, col.var = "cos2", gradient.cols = c("black", "red", "blue"), repel = TRUE)
fviz_cos2(pcapitcherpca, choice = "var", axes = 1:2) + scale_x_discrete(label = c("XWOBA", "Strikeout", "WOBA", "Batting Avg", "XBA", "On Base + SLG", "P/IP", "XLSG", "OBP", "XOBP", "K %", "SLG %", "AB", "PA", "XISO", "Single", "Hit", "P/Game", "BB %", "Double", "Barrel Batted Rate", "Exit Velocity Avg", "Launch Angle Avg", "Sweet Spot %", "Home Run", "Triple", "Player Age", "Walk")) + ggtitle("Cos2 Of Variables Assigned to Dimension 1 and 2 (Pitchers)")

fviz_pca_var(pcaallpca, col.var = "cos2", gradient.cols = c("black", "red", "blue"), repel = TRUE)
fviz_cos2(pcaallpca, choice = "var", axes = 1:2)
fviz_eig(pcabatterpca, addlabels = TRUE)
fviz_eig(pcapitcherpca, addlabels = TRUE)



```

```{r}
p_pitcher <- pitcherK %>%  plot_ly(x =~ xwoba, y=~ strikeout, z=~ batting_avg, color =~ as.factor(cluster), size =~ 1)
batterK
pitcherK
print(p_pitcher)

p_batter <- batterK %>%  plot_ly(x =~ single, y=~ batting_avg, z=~ xiso, color =~ as.factor(cluster), size =~ 1)
print(p_batter)
```



```{r}
res <- as.matrix(batterClust1) %>% Kmedians(nclust = 3, ninit = 0, niter = 20, 
                                            method = "Offline", init = TRUE, par = TRUE)


res1 <- (pitcherClust1) %>% Kmedians(nclust = 14, ninit = 0, niter = 20, 
                                            method = "Offline", init = TRUE, par = FALSE)

res1fviz = (res1$bestresult$cluster)



respam <- pam(scale_pitcher, 2, metric = "euclidean", stand = FALSE)


fviz_cluster(respam, scale_pitcher, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()) + ggtitle("Pitcher Cluster Using PAM") + xlab("Dimension 1 (37.8%)") + ylab("Dimension 2 (21%)")


respam1 <- pam(scale_batter, 2, metric = "euclidean", stand = FALSE)


fviz_cluster(respam1, scale_batter, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()) + ggtitle("Batter Cluster Using PAM")+ xlab("Dimension 1(39.2%)") + ylab("Dimension 2 (20.6%)")


respam2 <- pam(scale_all, 2, metric = "euclidean", stand = FALSE)


fviz_cluster(respam2, scale_all, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw())

```

```{r}

scale_pitcher <- scale(pitcherClust1)
scale_batter <- scale(batterClust1)
scale_all <- scale(allclust1)



fviz_nbclust(scale_pitcher, FUNcluster = kmeans ,  method = "silhouette", diss = NULL, k.max=15, print.summary = TRUE) + ggtitle("Optimal Number of Clusters for Pitchers Using Kmeans")

NbClust(data=scale_pitcher, diss = NULL, distance = "euclidean", min.nc=2, max.nc=15, method = "kmeans", index = "beale")



fviz_nbclust(scale_batter, FUNcluster = kmeans ,  method = "silhouette", diss = NULL, k.max=15) + ggtitle("Optimal Number of Clusters for Batters Using Kmeans")



fviz_nbclust(scale_all, FUNcluster = kmeans ,  method = "silhouette", diss = NULL, k.max=15)


fviz_silhouette(respam)
fviz_silhouette(respam1)
```
```{r}


#elbow kmeans
fviz_nbclust(scale_pitcher, FUNcluster = kmeans ,  method = "wss", diss = NULL, k.max=15, print.summary = TRUE)


fviz_nbclust(scale_batter, FUNcluster = kmeans ,  method = "wss", diss = NULL, k.max=15, print.summary = TRUE)


#elbow pam
fviz_nbclust(scale_pitcher, FUNcluster = pam ,  method = "wss", diss = NULL, k.max=15, print.summary = TRUE)


fviz_nbclust(scale_batter, FUNcluster = pam ,  method = "wss", diss = NULL, k.max=15, print.summary = TRUE)





```
```{r}
respam_elbow_batter <- pam(scale_batter, 5, metric = "euclidean", stand = FALSE)


fviz_cluster(respam_elbow_batter, scale_batter, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw())

fviz_silhouette(respam_elbow_batter)
```









```{r}
#gap statistics kmeans
fviz_nbclust(scale_pitcher, FUNcluster = kmeans ,  method = "gap", diss = NULL, k.max=15, print.summary = TRUE)

fviz_nbclust(scale_batter, FUNcluster = kmeans ,  method = "gap", diss = NULL, k.max=15, print.summary = TRUE)


#gap pam
fviz_nbclust(scale_pitcher, FUNcluster = pam ,  method = "gap", diss = NULL, k.max=15, print.summary = TRUE)

fviz_nbclust(scale_batter, FUNcluster = pam ,  method = "gap", diss = NULL, k.max=15, print.summary = TRUE)


```







```{r}






resK_pitcher <- kmeans(scale_pitcher, centers = 4, nstart = 20)
fviz_cluster(resK_pitcher, scale_pitcher, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()) + ggtitle("Pitcher Cluster Using Kmeans")+ xlab("Dimension 1 (37.8%)") + ylab("Dimension 2 (21%)")


resK_batter <- kmeans(scale_batter, centers = 2, nstart = 20)
fviz_cluster(resK_batter, scale_batter, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()) + ggtitle("Batter Cluster Using Kmeans")+ xlab("Dimension 1 (39.2%)") + ylab("Dimension 2 (20.6%)")


resK_all <- kmeans(scale_all, centers = 2, nstart = 20)
fviz_cluster(resK_all, scale_all, 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw())


plot(silhouette(resK_pitcher$cluster, dist_pitcher), col = 1:4,  border = NA)
plot(silhouette(resK_batter$cluster, dist_batter), col = 1:2,  border = NA)

```



```{r}
dist_pitcher <- dist(scale_pitcher, method = "euclidean")
dist_batter <- dist(scale_batter, method = "euclidean")

#hclust_avg_pitcher <- hclust(dist_pitcher, method = "ward.D")
#plot(hclust_avg_pitcher)
#cut_avg_pitcher <- cutree(hclust_avg_pitcher, h=2)

#hclust_avg_batter <- hclust(dist_batter, method = "ward.D")
#plot(hclust_avg_batter)


#library(dendextend)
#avg_dend_obj <- as.dendrogram(hclust_avg_pitcher)
#avg_col_dend <- color_branches(avg_dend_obj, h = 2)
#plot(avg_col_dend)

```





```{r}
batterK <- batter %>% mutate(cluster = resK_batter$cluster)
pitcherK <- pitcher %>% mutate(cluster = resK_pitcher$cluster)
allK <- allplayers %>% mutate(cluster = resK_all$cluster)

batterPam <- batter %>% mutate(cluster = respam1$clustering)
pitcherPam <- pitcher %>% mutate(cluster = respam$clustering)
allPam <- allplayers %>% mutate(cluster = respam2$clustering)


ggplot(data = batterK) + geom_histogram(aes(x=salary, fill = as.factor(cluster)))
ggplot(data = pitcherK) + geom_histogram(aes(x=salary, fill = as.factor(cluster)))
ggplot(data = allK) + geom_histogram(aes(x = salary, fill = as.factor(cluster)))

ggplot(data = batterPam) + geom_histogram(aes(x=salary, fill = as.factor(cluster)))
ggplot(data = pitcherPam) + geom_histogram(aes(x=salary, fill = as.factor(cluster)))
ggplot(data = allPam) + geom_histogram(aes(x = salary, fill = as.factor(cluster)))
```

```{r}
 batter %>% select(- `last_name, first_name`, -player_id, -year) %>% cor %>% corrplot()
pitcher %>% select(- `last_name, first_name`, -player_id, -year) %>% cor %>% corrplot()
pitcherK %>% ggplot() + geom_boxplot(aes(x=cluster, y = salary, group = cluster))
batterK %>% ggplot() + geom_boxplot(aes(x=cluster, y = salary, group = cluster))

pitcherPam %>% ggplot() + geom_boxplot(aes(x=cluster, y = salary, group = cluster))
batterPam %>% ggplot() + geom_boxplot(aes(x = cluster, y = salary, group = cluster))


```




```{r}
kruskal.test(salary ~ cluster, data = pitcherK)
kruskal_effsize(salary ~ cluster, data = pitcherK)
pairwise.wilcox.test(pitcherK$salary, pitcherK$cluster, p.adjust.method = "BH")

dunn_test(salary ~ cluster, p.adjust.method = "BH", data = pitcherK)
```

```{r}
kruskal.test(salary ~ cluster, data = batterK)
kruskal_effsize(salary ~ cluster, data = batterK)
pairwise.wilcox.test(batterK$salary, batterK$cluster, p.adjust.method = "BH")

dunn_test(salary ~ cluster, p.adjust.method = "BH", data = batterK)
```

```{r}
kruskal.test(salary ~ cluster, data = pitcherPam)
kruskal_effsize(salary ~ cluster, data = pitcherPam)
pairwise.wilcox.test(pitcherPam$salary, pitcherPam$cluster, p.adjust.method = "BH")

dunn_test(salary ~ cluster, p.adjust.method = "BH", data = pitcherPam)
```


```{r}
kruskal.test(salary ~ cluster, data = batterPam)
kruskal_effsize(salary ~ cluster, data = batterPam)
pairwise.wilcox.test(batterPam$salary, batterPam$cluster, p.adjust.method = "BH")

dunn_test(salary ~ cluster, p.adjust.method = "BH", data = batterPam)
```


```{r}
#pacoplot(batterClust, resK_batter$cluster)
#pacoplot(pitcherClust, resK_pitcher$cluster)
```


















